<template>
  <svg
    preserveAspectRatio="xMidYMid"
    viewBox="0 0 100 100"
    xmlns="http://www.w3.org/2000/svg"
    xmlns:xlink="http://www.w3.org/1999/xlink"
  >
    <circle
      cx="50"
      cy="50"
      fill="none"
      r="40"
      stroke="#386867"
      stroke-dasharray="62.83185307179586 62.83185307179586"
      stroke-linecap="round"
      stroke-width="6"
    >
      <animateTransform
        attributeName="transform"
        dur="2s"
        keyTimes="0;1"
        repeatCount="indefinite"
        type="rotate"
        values="0 50 50;360 50 50"
      />
    </circle>
    <circle
      cx="50"
      cy="50"
      fill="none"
      r="33"
      stroke="#F0E8D9"
      stroke-dasharray="51.83627878423159 51.83627878423159"
      stroke-dashoffset="51.83627878423159"
      stroke-linecap="round"
      stroke-width="6"
    >
      <animateTransform
        attributeName="transform"
        dur="2s"
        keyTimes="0;1"
        repeatCount="indefinite"
        type="rotate"
        values="0 50 50;-360 50 50"
      />
    </circle>
    <!-- [ldio] generated by https://loading.io/ -->
  </svg>
</template>
