import type { ValueOf } from '@lib/ui';

export const PERMISSIONS = {
  // EVENT CONTACTS
  EVENT_MNG: 'EVENT_MNG',
  EVENT_UPDATE: 'EVENT_UPDATE',
  EVENT_DELETE: 'EVENT_DELETE',

  // EVENT BRANDING
  EVENT_BRANDING_MNG: 'EVENT_BRANDING_MNG',
  EVENT_BRANDING_CREATE: 'EVENT_BRANDING_CREATE',
  EVENT_BRANDING_UPDATE: 'EVENT_BRANDING_UPDATE',
  EVENT_BRANDING_DELETE: 'EVENT_BRANDING_DELETE',

  // EVENT CONTACTS
  EVENT_CONTACTS_MNG: 'EVENT_CONTACTS_MNG',
  EVENT_CONTACTS_CREATE: 'EVENT_CONTACTS_CREATE',
  EVENT_CONTACTS_UPDATE: 'EVENT_CONTACTS_UPDATE',
  EVENT_CONTACTS_DELETE: 'EVENT_CONTACTS_DELETE',

  // EVENT PARKING_LOT
  EVENT_PARKING_LOT_MNG: 'EVENT_PARKING_LOT_MNG',
  EVENT_PARKING_LOT_CREATE: 'EVENT_PARKING_LOT_CREATE',
  EVENT_PARKING_LOT_UPDATE: 'EVENT_PARKING_LOT_UPDATE',
  EVENT_PARKING_LOT_DELETE: 'EVENT_PARKING_LOT_DELETE',
  EVENT_PARKING_LOT_COUNT_UPDATE: 'EVENT_PARKING_LOT_COUNT_UPDATE',

  // EVENT PROGRAM
  EVENT_PROGRAM_MNG: 'EVENT_PROGRAM_MNG',
  EVENT_PROGRAM_CREATE: 'EVENT_PROGRAM_CREATE',
  EVENT_PROGRAM_UPDATE: 'EVENT_PROGRAM_UPDATE',
  EVENT_PROGRAM_DELETE: 'EVENT_PROGRAM_DELETE',

  // EVENT USERS
  EVENT_USERS_MNG: 'EVENT_USERS_MNG',
  EVENT_USERS_VIEW: 'EVENT_USERS_VIEW',
  EVENT_USERS_CREATE: 'EVENT_USERS_CREATE',
  EVENT_USERS_UPDATE: 'EVENT_USERS_UPDATE',
  EVENT_USERS_DELETE: 'EVENT_USERS_DELETE',

  // EVENT GUEST LIST
  EVENT_GUEST_LIST_MNG: 'EVENT_GUEST_LIST_MNG',
  EVENT_GUEST_LIST_VIEW: 'EVENT_GUEST_LIST_VIEW',
  EVENT_GUEST_LIST_UPDATE: 'EVENT_GUEST_LIST_UPDATE',
  EVENT_GUEST_LIST_DELETE: 'EVENT_GUEST_LIST_DELETE',

  // EVENT ATTACHMENTS
  EVENT_ATTACHMENTS_MNG: 'EVENT_ATTACHMENTS_MNG',
  EVENT_ATTACHMENTS_CREATE: 'EVENT_ATTACHMENTS_CREATE',
  EVENT_ATTACHMENTS_UPDATE: 'EVENT_ATTACHMENTS_UPDATE',
  EVENT_ATTACHMENTS_DELETE: 'EVENT_ATTACHMENTS_DELETE',

  // EVENT SCHEDULE
  EVENT_SCHEDULE_MNG: 'EVENT_SCHEDULE_MNG',
  EVENT_SCHEDULE_CREATE: 'EVENT_SCHEDULE_CREATE',
  EVENT_SCHEDULE_UPDATE: 'EVENT_SCHEDULE_UPDATE',
  EVENT_SCHEDULE_DELETE: 'EVENT_SCHEDULE_DELETE',

  // EVENT FILES
  EVENT_FILES_MNG: 'EVENT_FILES_MNG',
  EVENT_FILES_CREATE: 'EVENT_FILES_CREATE',
  EVENT_FILES_UPDATE: 'EVENT_FILES_UPDATE',
  EVENT_FILES_DELETE: 'EVENT_FILES_DELETE',
} as const;

export type Permissions = ValueOf<typeof PERMISSIONS>;
